# Generated by Django 3.1.7 on 2021-03-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210328_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='sRollNo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
